import type { Platform, StrategyTier } from "@shared/schema";

export const platforms: Platform[] = [
  {
    id: "claude-sonnet",
    name: "Claude (Sonnet 4)",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Best-in-class for coding, analysis, and nuanced reasoning with superior safety guardrails.",
    marketShare: "12%",
    pricing: "$20/user/month",
    contextWindow: "200K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, Analysts, Researchers",
    capabilities: {
      codeGeneration: 10,
      reasoning: 10,
      languageUnderstanding: 9,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 8,
      enterpriseFeatures: 9,
      developerExperience: 9,
      documentation: 9,
    },
    logoColor: "#D97706",
  },
  {
    id: "chatgpt-enterprise",
    name: "ChatGPT Enterprise",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Most widely adopted with excellent general-purpose capabilities and strong ecosystem.",
    marketShare: "38%",
    pricing: "$60/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Enterprise Teams, Knowledge Workers",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 9,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
    },
    logoColor: "#10A37F",
  },
  {
    id: "gemini-advanced",
    name: "Gemini Advanced",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Excellent for research with massive context window and deep Google ecosystem integration.",
    marketShare: "15%",
    pricing: "$20/user/month",
    contextWindow: "1M tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Researchers, Google Workspace Users",
    capabilities: {
      codeGeneration: 8,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 10,
      toolUse: 8,
      speed: 9,
      costEfficiency: 9,
      enterpriseFeatures: 8,
      developerExperience: 7,
      documentation: 8,
    },
    logoColor: "#4285F4",
  },
  {
    id: "microsoft-copilot",
    name: "Microsoft Copilot",
    category: "Enterprise",
    priority: "Tier 1",
    verdict: "Seamless Microsoft 365 integration for enterprise productivity at scale.",
    marketShare: "18%",
    pricing: "$30/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR", "FedRAMP"],
    targetUsers: "Microsoft 365 Users, Enterprise",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
    },
    logoColor: "#00A4EF",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "Specialized",
    priority: "Tier 1",
    verdict: "Industry-leading code completion and generation for software developers.",
    marketShare: "8%",
    pricing: "$10-20/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2"],
    targetUsers: "Software Developers",
    capabilities: {
      codeGeneration: 10,
      reasoning: 7,
      languageUnderstanding: 7,
      multimodal: 3,
      toolUse: 8,
      speed: 9,
      costEfficiency: 9,
      enterpriseFeatures: 7,
      developerExperience: 10,
      documentation: 8,
    },
    logoColor: "#24292E",
  },
  {
    id: "perplexity-pro",
    name: "Perplexity Pro",
    category: "Specialized",
    priority: "Tier 2",
    verdict: "Best-in-class research assistant with real-time web search and citations.",
    marketShare: "3%",
    pricing: "$20/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Researchers, Analysts",
    capabilities: {
      codeGeneration: 6,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 9,
      speed: 9,
      costEfficiency: 8,
      enterpriseFeatures: 6,
      developerExperience: 7,
      documentation: 7,
    },
    logoColor: "#20808D",
  },
  {
    id: "anthropic-api",
    name: "Anthropic API",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Direct API access to Claude models with flexible pricing for custom integrations.",
    marketShare: "5%",
    pricing: "Pay-per-token",
    contextWindow: "200K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, API Integrators",
    capabilities: {
      codeGeneration: 10,
      reasoning: 10,
      languageUnderstanding: 9,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 7,
      developerExperience: 9,
      documentation: 9,
    },
    logoColor: "#D97706",
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Most extensive API ecosystem with GPT-4 and specialized models for any use case.",
    marketShare: "25%",
    pricing: "Pay-per-token",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, Enterprises",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 9,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 8,
      developerExperience: 9,
      documentation: 10,
    },
    logoColor: "#10A37F",
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Multi-model platform deeply integrated with AWS services for enterprise scale.",
    marketShare: "4%",
    pricing: "Variable",
    contextWindow: "Variable",
    compliance: ["SOC2", "HIPAA", "FedRAMP"],
    targetUsers: "AWS Customers, Enterprise",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 8,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
    },
    logoColor: "#FF9900",
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "OpenAI models with Azure enterprise security, compliance, and regional data residency.",
    marketShare: "6%",
    pricing: "Variable",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "FedRAMP", "GDPR"],
    targetUsers: "Azure Customers, Government",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 8,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
    },
    logoColor: "#0078D4",
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "Developer",
    priority: "Tier 3",
    verdict: "Specialized NLP platform with excellent embedding models and enterprise search.",
    marketShare: "2%",
    pricing: "Pay-per-token",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "NLP Developers, Search Teams",
    capabilities: {
      codeGeneration: 6,
      reasoning: 7,
      languageUnderstanding: 9,
      multimodal: 4,
      toolUse: 6,
      speed: 9,
      costEfficiency: 8,
      enterpriseFeatures: 7,
      developerExperience: 8,
      documentation: 7,
    },
    logoColor: "#39594D",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "Developer",
    priority: "Tier 3",
    verdict: "Open model hub with thousands of models and excellent fine-tuning capabilities.",
    marketShare: "3%",
    pricing: "Free-Variable",
    contextWindow: "Variable",
    compliance: ["GDPR"],
    targetUsers: "ML Engineers, Researchers",
    capabilities: {
      codeGeneration: 7,
      reasoning: 7,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 6,
      speed: 7,
      costEfficiency: 10,
      enterpriseFeatures: 5,
      developerExperience: 8,
      documentation: 9,
    },
    logoColor: "#FFD21E",
  },
  {
    id: "jasper",
    name: "Jasper",
    category: "Specialized",
    priority: "Tier 2",
    verdict: "Purpose-built for marketing teams with brand voice training and campaign tools.",
    marketShare: "2%",
    pricing: "$49/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Marketing Teams, Content Creators",
    capabilities: {
      codeGeneration: 2,
      reasoning: 6,
      languageUnderstanding: 8,
      multimodal: 6,
      toolUse: 7,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 7,
      developerExperience: 5,
      documentation: 7,
    },
    logoColor: "#FF5A5F",
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    category: "Specialized",
    priority: "Tier 3",
    verdict: "Sales-focused copywriting platform with workflow automation for GTM teams.",
    marketShare: "1%",
    pricing: "$49/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Sales Teams, Marketers",
    capabilities: {
      codeGeneration: 1,
      reasoning: 5,
      languageUnderstanding: 7,
      multimodal: 4,
      toolUse: 6,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 6,
      developerExperience: 5,
      documentation: 6,
    },
    logoColor: "#7C3AED",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "Productivity",
    priority: "Tier 2",
    verdict: "Seamlessly integrated AI for knowledge management within the Notion ecosystem.",
    marketShare: "2%",
    pricing: "$10/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Notion Users, Knowledge Workers",
    capabilities: {
      codeGeneration: 4,
      reasoning: 6,
      languageUnderstanding: 7,
      multimodal: 5,
      toolUse: 8,
      speed: 8,
      costEfficiency: 9,
      enterpriseFeatures: 6,
      developerExperience: 5,
      documentation: 7,
    },
    logoColor: "#000000",
  },
  {
    id: "slack-ai",
    name: "Slack AI",
    category: "Productivity",
    priority: "Tier 3",
    verdict: "Channel summaries and thread insights for teams already living in Slack.",
    marketShare: "1%",
    pricing: "$10/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Slack Users, Team Collaboration",
    capabilities: {
      codeGeneration: 2,
      reasoning: 5,
      languageUnderstanding: 7,
      multimodal: 3,
      toolUse: 7,
      speed: 8,
      costEfficiency: 8,
      enterpriseFeatures: 7,
      developerExperience: 4,
      documentation: 6,
    },
    logoColor: "#4A154B",
  },
];

export const strategyTiers: StrategyTier[] = [
  {
    tier: 1,
    name: "Foundation",
    description: "Core platforms for broad enterprise adoption with proven ROI",
    platforms: ["claude-sonnet", "chatgpt-enterprise", "github-copilot", "microsoft-copilot"],
    rationale: "Tier 1 platforms offer the best balance of capability, enterprise features, and market maturity. Start here for maximum impact with minimal risk.",
  },
  {
    tier: 2,
    name: "Specialization",
    description: "Domain-specific tools for targeted use cases and power users",
    platforms: ["perplexity-pro", "jasper", "notion-ai", "anthropic-api", "openai-api"],
    rationale: "After establishing foundation tools, add specialized platforms for specific workflows like research, marketing, and custom integrations.",
  },
  {
    tier: 3,
    name: "Advanced",
    description: "Cutting-edge and experimental platforms for innovation teams",
    platforms: ["aws-bedrock", "azure-openai", "cohere", "huggingface", "copy-ai", "slack-ai"],
    rationale: "Advanced platforms for teams with mature AI adoption seeking fine-tuning, custom models, or experimental capabilities.",
  },
];

export const capabilityLabels: Record<keyof Platform["capabilities"], string> = {
  codeGeneration: "Code Generation",
  reasoning: "Reasoning",
  languageUnderstanding: "Language Understanding",
  multimodal: "Multimodal",
  toolUse: "Tool Use",
  speed: "Speed",
  costEfficiency: "Cost Efficiency",
  enterpriseFeatures: "Enterprise Features",
  developerExperience: "Developer Experience",
  documentation: "Documentation",
};

export const matrixFeatures = [
  { category: "Core Capabilities", features: ["codeGeneration", "reasoning", "languageUnderstanding", "multimodal", "toolUse", "speed"] },
  { category: "Enterprise & Cost", features: ["costEfficiency", "enterpriseFeatures", "developerExperience", "documentation"] },
];
